{{- if .Values.priorityClasses.giantswarmCritical.enabled }}
{{- $render := false -}}
{{- $existing := lookup "scheduling.k8s.io/v1" "PriorityClass" "" "giantswarm-critical" -}}
{{- if not $existing -}}
{{- $render = true -}}
{{- else -}}
{{- if $existing.metadata.labels -}}
{{- if eq (index $existing.metadata.labels "app.kubernetes.io/instance") .Release.Name -}}
{{- $render = true -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if $render -}}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: giantswarm-critical
  labels:
    {{- include "priority-classes.labels" . | nindent 4 }}
value: {{ .Values.priorityClasses.giantswarmCritical.value }}
globalDefault: false
description: {{ .Values.priorityClasses.giantswarmCritical.description | quote }}
{{- end -}}
{{- end }}

