{{- if .Values.priorityClasses.giantswarmCritical.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: giantswarm-critical
  labels:
    {{- include "priority-classes.labels" . | nindent 4 }}
value: {{ .Values.priorityClasses.giantswarmCritical.value }}
globalDefault: false
description: {{ .Values.priorityClasses.giantswarmCritical.description | quote }}
{{- end }}

