apiVersion: v2
version: 0.3.1
name: priority-classes
description: Standardized PriorityClass resources for Giant Swarm clusters, providing giantswarm-critical and giantswarm-high priority levels
home: https://github.com/giantswarm/priority-classes
icon: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
sources:
  - https://github.com/giantswarm/priority-classes
annotations:
  application.giantswarm.io/team: tenet
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
maintainers:
  - name: Team Tenet
    email: team-tenet@giantswarm.io
