apiVersion: v2
appVersion: 0.1.0
version: 0.1.0
name: priority-classes
description: Standardized PriorityClass resources for Giant Swarm clusters, providing giantswarm-critical and giantswarm-high priority levels
home: https://github.com/giantswarm/priority-classes
# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
#icon: https://s.giantswarm.io/app-icons/priority-classes/1/light.svg
sources:
  - https://github.com/giantswarm/priority-classes
annotations:
  application.giantswarm.io/team: tenet
maintainers:
  - name: Team Tenet
    email: team-tenet@giantswarm.io
